# Generated by Django 3.2 on 2021-04-22 11:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0002_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='price',
            field=models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator]),
            preserve_default=False,
        ),
    ]
