# Generated by Django 3.2 on 2021-04-27 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0005_auto_20210427_0935'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='books_number',
        ),
    ]
